version: '2.0'
services:


  amtadminer:
    image: amtadminer
    build: ../images/adminer
    restart: always
    ports:
      - "8080:8080"
  amtdb:
    image: amtdb
    build: ../images/mysql
    restart: always
    ports:
      - "3306:3306"
  amtspringboot:
    image: amtspringboot
    build: ../images/springboot
    environment:
      - DATABASE_SERVER_ADDRESS=amtdb
      - SPRING_SERVER_PORT=8080
      - DATABASE_SERVER_PORT=3306
      - DATABASE_USERNAME=amtdb
      - DATABASE_PASSWORD=amtdb
      - DATABASE_NAME=amtdb
    ports:
     - "8081:8080"
  failsafe:
    image: failsafe
    build: ../images/failsafe
    environment:
      - URL=http://amtspringboot:8080
    volumes:
      - failsafedep:/root/.m2

volumes:
  failsafedep:
