version: '2.0'
services:
  amtadminer:
    image: amtadminer
    build: ../images/adminer
    restart: always
    ports:
      - "8080:8080"
  amtdb:
    image: amtdb
    build: ../images/mysql
    restart: always
    ports:
      - "3306:3306"
  amtspringboot:
    image: amtspringboot
    build: ../images/springboot
    environment:
      - DATABASE_SERVER_ADDRESS=amtdb
      - SPRING_SERVER_PORT=8080
      - DATABASE_SERVER_PORT=3306
      - DATABASE_USERNAME=amtdb
      - DATABASE_PASSWORD=amtdb
      - DATABASE_NAME=amtdb
    ports:
     - "8081:8080"

  mvnruntest:
    image: amtruntest
    build: ../images/mvnruntest
    environment:
      - URL=http://amtspringboot:8080
    depends_on:
      - amtspringboot
