version: "3"
services:
  GamificationAPI:
    image: amtspringboot
    build: ../images/gamification-engine
    environment:
      - DATABASE_SERVER_ADDRESS=amtdb
      - SPRING_SERVER_PORT=8080
      - DATABASE_SERVER_PORT=3306
      - DATABASE_USERNAME=amtdb
      - DATABASE_PASSWORD=amtdb
      - DATABASE_NAME=amtdb
    ports:
      - "8086:8080"
    restart: always
    depends_on:
      - amtdb 
  amtdb:  
    image: amtdb
    build: ../images/mysql
    restart: always
    ports:
      - "3306:3306"
